# Generated by Django 3.0.3 on 2020-02-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20200211_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='departure',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
